name: Node CI

on: [pull_request]

jobs:
  linter:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [">=16.9", 18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install node-canvas dependencies
      run: |
        sudo apt update
        sudo apt install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev
      if: matrix.node-version == 18.x

    - name: Install npm dependencies
      run: npm install
      run: npm install -g tsc

    - run: npm run lint


