name: Node CI

on: [pull_request]

jobs:
  linter:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [">=16.9", 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install node-canvas dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

    - name: Install npm dependencies
      run: |
        npm i -g tsc
        npm ci

    - name: Run ESLint
      run: npm run lint


